# Generated by Django 4.2.3 on 2023-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('total', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
