# Generated by Django 4.2.3 on 2023-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item',
            field=models.CharField(max_length=15),
        ),
    ]
