version: '3.8'

services:
 db:
  image: postgres:13.0-alpine
  volumes:
    - /var/lib/postgresql/data/
  env_file:
    - .env

 gems:
   build:
     dockerfile: Dockerfile
   image: gems:latest
   ports:
    - "8000:8000"
   restart: always
   depends_on:
     - db
   env_file:
     - .env
